/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
#include <activemq/connector/openwire/commands/DiscoveryEvent.h>
#include <activemq/exceptions/ActiveMQException.h>
#include <decaf/lang/exceptions/NullPointerException.h>
#include <memory>

using namespace std;
using namespace activemq;
using namespace activemq::exceptions;
using namespace activemq::connector;
using namespace activemq::connector::openwire;
using namespace activemq::connector::openwire::commands;
using namespace decaf::lang::exceptions;

/*
 *
 *  Command and marshaling code for OpenWire format for DiscoveryEvent
 *
 *
 *  NOTE!: This file is autogenerated - do not modify!
 *         if you need to make a change, please see the Java Classes in the
 *         activemq-core module
 *
 */
////////////////////////////////////////////////////////////////////////////////
DiscoveryEvent::DiscoveryEvent()
{
    this->serviceName = "";
    this->brokerName = "";
}

////////////////////////////////////////////////////////////////////////////////
DiscoveryEvent::~DiscoveryEvent()
{
}

////////////////////////////////////////////////////////////////////////////////
DiscoveryEvent* DiscoveryEvent::cloneDataStructure() const {
    std::auto_ptr<DiscoveryEvent> discoveryEvent( new DiscoveryEvent() );

    // Copy the data from the base class or classes
    discoveryEvent->copyDataStructure( this );

    return discoveryEvent.release();
}

////////////////////////////////////////////////////////////////////////////////
void DiscoveryEvent::copyDataStructure( const DataStructure* src ) {

    // Copy the data of the base class or classes
    BaseDataStructure::copyDataStructure( src );

    const DiscoveryEvent* srcPtr = dynamic_cast<const DiscoveryEvent*>( src );

    if( srcPtr == NULL || src == NULL ) {

        throw decaf::lang::exceptions::NullPointerException(
            __FILE__, __LINE__,
            "DiscoveryEvent::copyDataStructure - src is NULL or invalid" );
    }
    this->setServiceName( srcPtr->getServiceName() );
    this->setBrokerName( srcPtr->getBrokerName() );
}

////////////////////////////////////////////////////////////////////////////////
unsigned char DiscoveryEvent::getDataStructureType() const {
    return DiscoveryEvent::ID_DISCOVERYEVENT;
}

////////////////////////////////////////////////////////////////////////////////
std::string DiscoveryEvent::toString() const {

    ostringstream stream;

    stream << "Begin Class = DiscoveryEvent" << std::endl;
    stream << " Value of DiscoveryEvent::ID_DISCOVERYEVENT = 40" << std::endl;
    stream << " Value of ServiceName = " << this->getServiceName() << std::endl;
    stream << " Value of BrokerName = " << this->getBrokerName() << std::endl;
    stream << BaseDataStructure::toString();
    stream << "End Class = DiscoveryEvent" << std::endl;

    return stream.str();
}

////////////////////////////////////////////////////////////////////////////////
bool DiscoveryEvent::equals( const DataStructure* value ) const {
    const DiscoveryEvent* valuePtr = dynamic_cast<const DiscoveryEvent*>( value );

    if( valuePtr == NULL || value == NULL ) {
        return false;
    }
    if( this->getServiceName() != valuePtr->getServiceName() ) {
        return false;
    }
    if( this->getBrokerName() != valuePtr->getBrokerName() ) {
        return false;
    }
    if( !BaseDataStructure::equals( value ) ) {
        return false;
    }
    return true;
}

////////////////////////////////////////////////////////////////////////////////
const std::string& DiscoveryEvent::getServiceName() const {
    return serviceName;
}

////////////////////////////////////////////////////////////////////////////////
std::string& DiscoveryEvent::getServiceName() {
    return serviceName;
}

////////////////////////////////////////////////////////////////////////////////
void DiscoveryEvent::setServiceName(const std::string& serviceName ) {
    this->serviceName = serviceName;
}

////////////////////////////////////////////////////////////////////////////////
const std::string& DiscoveryEvent::getBrokerName() const {
    return brokerName;
}

////////////////////////////////////////////////////////////////////////////////
std::string& DiscoveryEvent::getBrokerName() {
    return brokerName;
}

////////////////////////////////////////////////////////////////////////////////
void DiscoveryEvent::setBrokerName(const std::string& brokerName ) {
    this->brokerName = brokerName;
}

